openapi: 3.0.0
info:
  title: Model Postgres Service
  version: 1.0.0

paths:
  /v1/send/sms:
    post:
      summary: Take the message and send it to the contact by contactId
      
      parameters:
        - name: Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
          description: Unique key to prevent duplicate SMS sending

        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: JWT
      
      requestBody:
        $ref: '#/components/requests/SendSmsRequest'

      responses:
        '202':
          description: Accepted
          $ref: '#/components/responses/SendSmsResponse'
          
        '400':
          description: Bad request
          $ref: '#/components/responses/ErrorWithCode'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/ErrorWithCode'
        '429':
          description: Too Many Requests
          $ref: '#/components/responses/ErrorWithCode'
        '500':
          description: Internal Server Error
          $ref: '#/components/responses/ErrorWithCode'

  /v1/contact:
    post:
      summary: Create the contact
      
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: JWT
      
      requestBody:
        description: Request without body

      responses:
        '201':
          description: Created
          $ref: '#/components/requests/CreateContactResponse'
          
        '400':
          description: Bad request
          $ref: '#/components/responses/ErrorWithCode'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/ErrorWithCode'
        '429':
          description: Too Many Requests
          $ref: '#/components/responses/ErrorWithCode'
        '500':
          description: Internal Server Error
          $ref: '#/components/responses/ErrorWithCode'

  /v1/contact/{contactId}:
    patch:
      summary: Modify the contact
      
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: JWT
      
        - name: contactId
          in: path
          description: UUID of contact
          schema:
            type: string
            format: uuid
        
      requestBody:
        $ref: '#/components/requests/ModifyContactRequest'

      responses:
        '200':
          description: Modified
          $ref: '#/components/requests/ModifyContactResponse'
          
        '400':
          description: Bad request
          $ref: '#/components/responses/ErrorWithCode'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/ErrorWithCode'
        '429':
          description: Too Many Requests
          $ref: '#/components/responses/ErrorWithCode'
        '500':
          description: Internal Server Error
          $ref: '#/components/responses/ErrorWithCode'

  /v1/contact/{contactId}/connection:
    post:
      summary: Create the new connection
      
      parameters:
        - name: contactId
          in: path
          description: UUID of contact
          schema:
            type: string
            format: uuid
        
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: JWT
      
      requestBody:
        $ref: '#/components/requests/CreateConnectionRequest'

      responses:
        '201':
          description: Created successfully
          $ref: '#/components/requests/CreateConnectionResponse'
          
        '400':
          description: Bad request
          $ref: '#/components/responses/ErrorWithCode'
        '401':
          description: Unauthorized
          $ref: '#/components/responses/ErrorWithCode'
        '403':
          description: Forbidden
          $ref: '#/components/responses/ErrorWithCode'
        '429':
          description: Too Many Requests
          $ref: '#/components/responses/ErrorWithCode'
        '500':
          description: Internal Server Error
          $ref: '#/components/responses/ErrorWithCode'
          
  /v1/contact:
    get:
      summary: Get all contacts

      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: JWT

      responses:
        '200':
          description: OK
          $ref: '#/components/responses/GetAllContactsResponse'

        '401':
          description: Unauthorized
          $ref: '#/components/responses/ErrorWithCode'
        '500':
          description: Internal Server Error
          $ref: '#/components/responses/ErrorWithCode'

  /v1/contact/{contactId}/connection:
    get:
      summary: Get all connections for contact

      parameters:
        - name: contactId
          in: path
          required: true
          schema:
            type: string
            format: uuid

        - name: Authorization
          in: header
          required: true
          schema:
            type: string

      responses:
        '200':
          description: OK
          $ref: '#/components/responses/GetAllConnectionsResponse'

        '401':
          description: Unauthorized
          $ref: '#/components/responses/ErrorWithCode'
        '403':
          description: Forbidden
          $ref: '#/components/responses/ErrorWithCode'
        '500':
          description: Internal Server Error
          $ref: '#/components/responses/ErrorWithCode'

components:
  requestBodies:
    'SendSmsRequest':
      required: true
      content:
        application/json:
          schema:
            $ref: './components/schemas.yaml#/components/schemas/SendSmsRequest'

    'ModifyContactRequest':
      required: true
      content:
        application/json:
          schema:
            $ref: './components/schemas.yaml#/components/schemas/ModifyContactRequest'

    'CreateConnectionRequest':
      required: true
      content:
        application/json:
          schema:
            $ref: './components/schemas.yaml#/components/schemas/CreateConnectionRequest'

  responses:
    'SendSmsResponse':
      description: 'Response on success'
      content:
        application/json:
          schema:
            $ref: './components/errors.yaml#/components/schemas/SendSmsResponse'

    'CreateContactResponse':
      description: 'Response on success'
      content:
        application/json:
          schema:
            $ref: './components/errors.yaml#/components/schemas/CreateContactResponse'

    'ModifyContactResponse':
      description: 'Response on success'
      content:
        application/json:
          schema:
            $ref: './components/errors.yaml#/components/schemas/ModifyContactResponse'

    'CreateConnectionResponse':
      required: true
      content:
        application/json:
          schema:
            $ref: './components/schemas.yaml#/components/schemas/CreateConnectionResponse'

    'GetAllContactsResponse':
      description: 'Response on success'
      content:
        application/json:
          schema:
            $ref: './components/schemas.yaml#/components/schemas/GetAllContactsResponse'

    'GetAllConnectionsResponse':
      description: 'Response on success'
      content:
        application/json:
          schema:
            $ref: './components/schemas.yaml#/components/schemas/GetAllConnectionsResponse'

    'ErrorWithCode':
      description: 'Error with code and message'
      content:
        application/json:
          schema:
            $ref: './components/errors.yaml#/components/schemas/ErrorResponse'

